apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-settings
data:
  SECRET_API_KEY: {{ .Values.apiKey | b64enc }}
  GROWTHBOOK_API_HOST: {{ .Values.apiHost | b64enc }}
  NODE_ENV: {{ .Values.apiHost | b64enc }}
  CACHE_ENGINE: {{ .Values.cacheEngine | b64enc }}
  CACHE_CONNECTION_URL: {{ .Values.cacheConnectionUrl | b64enc }}
  CACHE_STALE_TTL: {{ .Values.cacheStaleTtl | b64enc }}
  CACHE_EXPIRES_TTL: {{ .Values.cacheExpiresTtl | b64enc }}
  USE_HTTP2: {{ .Values.useHttp2 | b64enc }}
  HTTPS_CERT: {{ .Values.httpsCert | b64enc }}
  HTTPS_KEY: {{ .Values.httpsKey | b64enc }}
  ENABLE_REMOTE_EVAL: {{ .Values.enableRemoteEval | b64enc }}
  MAX_PAYLOAD_SIZE: {{ .Values.maxPayloadSize | b64enc }}
  VERBOSE_DEBUGGING: {{ .Values.verboseDebugging | b64enc }}
  PUBLISH_PAYLOAD_TO_CHANNEL: {{ .Values.horizontalScaling.publishPayloadToChannel | b64enc }}
  # Redis
  USE_CLUSTER: {{ .Values.redisCluster.enabled | b64enc }}
  CLUSTER_ROOT_NODES: {{ .Values.redisCluster.redisRootNodes | b64enc }}
  CLUSTER_ROOT_NODES_JSON: {{ .Values.redisCluster.redisRootNodesJson | b64enc }}
  CLUSTER_OPTIONS_JSON: {{ .Values.redisCluster.redisOptionsJson | b64enc }}
  # Mongo
  CACHE_DATABASE_NAME: {{ .Values.mongoDb.databaseName | b64enc }}
  CACHE_COLLECTION_NAME: {{ .Values.mongoDb.collectionName | b64enc }}
  # streaming
  ENABLE_EVENT_STREAM: {{ .Values.streaming.enabled | b64enc }}
  EVENT_STREAM_MAX_DURATION_MS: {{ .Values.streaming.maxDuration | b64enc }}
  EVENT_STREAM_PING_INTERVAL_MS: {{ .Values.streaming.pingInterval | b64enc }}
