apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-settings
data:
  SECRET_API_KEY: {{ .Values.apiKey | b64enc }}
  GROWTHBOOK_API_HOST: {{ .Values.apiHost | b64enc }}
  NODE_ENV: {{ .Values.apiHost | b64enc }}
  CACHE_ENGINE: {{ .Values.cacheEngine | b64enc }}
  CACHE_CONNECTION_URL: {{ .Values.cacheConnectionUrl | b64enc }}
  CACHE_STALE_TTL: {{ .Values.cacheStaleTtl | b64enc }}
  CACHE_EXPIRES_TTL: {{ .Values.cacheExpiresTtl | b64enc }}
  USE_HTTP2: {{ .Values.useHttp2 | b64enc }}
  HTTPS_CERT: {{ .Values.httpsCert | b64enc }}
  HTTPS_KEY: {{ .Values.httpsKey | b64enc }}
